sudo: required
services:
   - docker
before_install:
   - docker build -t imran2329/dokcer_practice -f Dockerfile.dev .

scrips:
   - docker run imran2329/dokcer_practice npm run test -- --coverage


